### ISSUE TITLE
Server Error, HTTP 500: Unhandled exception occured

### ISSUE THREAD

**Issue by nosferatu500** [riganti/dotvvm-samples-academy#1]
When I Click on Lesson 3....
![capture](https://cloud.githubusercontent.com/assets/9116892/23101484/eb196284-f6c6-11e6-99bc-a616c6fd11c1.PNG)

Fix please...
![capture](https://cloud.githubusercontent.com/assets/9116892/23101619/51c39e98-f6ca-11e6-9ad0-616b7fc42598.PNG)

**Comment by nosferatu500** [comment]
From Solution all work fine (non-debug mode), but on site I get Error: 500

**Comment by Arcidev** [comment]
Looks like its fixed then. I've also encountered some bugs on site that are already fixed in this repo.

**Comment by tomasherceg** [comment]
I’ll deploy the latest version in a few hours.

Sent from my Windows 10 phone

**Comment by tomasherceg** [comment]
Fixed, sorry about the issues.
